#!/usr/bin/env bash

set -eou pipefail

usages() {
  cat <<EOT
Hermes is a cli script performs different tasks in HermesIII project development

Available commands
* up       Start the development environment
* down     Stop and clean the development environment
  Options:
    all    Clean up docker images and containers
* psql     Interactive connect to psql
* help     Show command usages
  --help
  -h

Example usages

  ./hermes up
  ./hermes down all
  ./hermes psql
EOT
}

main() {
  while [[ $# -gt 0 ]]; do
    opt=$1

    shift;
    case "${opt}" in
      "help"|"--help"|"-h" )
        usages
        ;;
      "up"|"down"|"psql" )
        ./scripts/${opt} $@
        ;;
      * )
        readonly green="\e[0;92m"
        readonly reset="\e[0m"

        echo -e "\n${green}Command isn't supported. Please check the usages${reset}\n"
        usages
        exit 1
        ;;
    esac
  done
}

main "$@"
