#!/usr/bin/env bash

set -eou pipefail

main() {
  if [ ! -z "$(docker-compose ps -q postgresql)" ]; then
    docker-compose exec postgresql psql -U postgres -d hermes3_development_db
  else
    echo "Postgresql service isn't up, did you run 'scripts/up' yet"
    exit 1
  fi
}

main
