#!/usr/bin/env bash

set -eou pipefail

install() {
  local -r pkg=$1

  if [[ $(uname) =~ 'Darwin' ]]; then
    brew install ${pkg}
  else
    echo "--- Missing required softwares! Please ensure you have docker and docker-compose installed on your machine.\n You can find Docker for Desktop here https://www.docker.com/products/docker-desktop"
    exit 1
  fi
}

ensure_brew_is_installed() {
  if [ -z $(type -p brew) ]; then
    xcode-select --install || :
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    brew update
  fi
}

check_prerequisite() {
  packages=(docker docker-compose)

  for pkg in "${packages[@]}"; do
    if [ -z $(type -p "${pkg}") ]; then
      install "${pkg}"
    fi
  done

  if [ -z "$(brew list --cask | grep docker)" ]; then
    brew install --cask docker
    open /Applications/Docker.app/
  fi
}

migrate_db() {
  docker-compose exec web npm run db:migrate
}

add_host_entry() {
  readonly host_entry="0.0.0.0 hermesiii.local.dev"

  if [ -z "$(grep "${host_entry}" '/etc/hosts')" ]; then
    cp /etc/hosts ~/.host.original.backup

    echo "${host_entry}" | sudo tee -a /etc/hosts > /dev/null
  fi

  readonly green="\033[0;92m"
  readonly reset="\033[0m"

  echo -e "${green}Access the local site at http://hermesiii.local.dev${reset}"
}

main() {
  sudo -v
  ensure_brew_is_installed
  check_prerequisite

  docker-compose up -d --build
  migrate_db

  add_host_entry
}

main
